schema_version: 1

context:
  name: apache-airflow-providers-google
  version: "22.3.0"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/apache_airflow_providers_google-${{ version }}.tar.gz
  sha256: 3721f23cd0d187eebb3600bcbcd0ba31e4113d3b1abb081cdeed23500cd862d8

build:
  number: 0
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python
    - pip
    - flit-core ==3.12.0
  run:
    - python
tests:
  - python:
      imports:
        - airflow.providers.google
      pip_check: true

about:
  summary: Provider package apache-airflow-providers-google for Apache Airflow
  license: Apache-2.0
  license_file:
    - LICENSE
    - NOTICE
  homepage: https://github.com/apache/airflow/
  repository: https://github.com/apache/airflow/
  documentation: https://airflow.apache.org/docs/apache-airflow-providers-google/stable/index.html

extra:
  recipe-maintainers:
    - xylar
