schema_version: 1

context:
  name: apache-airflow-providers-google
  version: "22.3.0"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/apache_airflow_providers_google-${{ version }}.tar.gz
  sha256: 3721f23cd0d187eebb3600bcbcd0ba31e4113d3b1abb081cdeed23500cd862d8

build:
  number: 0
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python
    - pip
    - flit-core ==3.12.0
  run:
    - python
    - apache-airflow >=2.11.0
    - apache-airflow-providers-common-compat >=1.13.0
    - apache-airflow-providers-common-sql >=1.32.0
    - asgiref >=3.5.2
    - dill >=0.2.3
    - gcloud-aio-auth >=5.2.0
    - gcloud-aio-bigquery >=6.1.2
    - gcloud-aio-storage >=9.0.0
    - gcsfs >=2023.10.0
    - google-ads >=26.0.0,!=28.0.0.post2
    - google-analytics-admin >=0.9.0
    - google-api-core >=2.30.3
    - google-api-python-client >=2.0.2
    - google-auth >=2.29.0
    - google-auth-httplib2 >=0.0.1
    - google-genai >=2.8.0
    - google-cloud-aiplatform >=1.155.0
    - tqdm >=4.23.0
    - scikit-learn >=1.6.0
    - jsonschema >=4.19.1
    - ruamel.yaml >=0.19.0
    - pyyaml >=6.0.3
    - litellm >=1.83.7,<1.86.0
    - if: match(python, "<3.13")
      then: ray-default >=2.42.0
      else: ray-default >=2.49.0
    - if: match(python, "<3.13")
      then: google-cloud-bigquery-storage >=2.31.0
      else: google-cloud-bigquery-storage >=2.33.0
    - google-cloud-alloydb >=0.4.0
    - google-cloud-automl >=2.12.0
    - google-cloud-bigquery-core >=3.24.0
    - google-cloud-bigquery-datatransfer >=3.13.0
    - google-cloud-bigtable >=2.17.0
    - google-cloud-build >=3.31.0
    - google-cloud-compute >=1.10.0
    - google-cloud-container >=2.52.0
    - google-cloud-datacatalog >=3.23.0
    - google-cloud-dataflow-client >=0.8.6
    - google-cloud-dataform >=0.5.0
    - google-cloud-dataplex >=2.6.0
    - google-cloud-dataproc >=5.27.0
    - google-cloud-dataproc-metastore >=1.12.0
    - google-cloud-dlp >=3.12.0
    - google-cloud-kms >=2.15.0
    - google-cloud-language >=2.9.0
    - google-cloud-logging >=3.5.0
    - google-cloud-managedkafka >=0.1.6
    - google-cloud-memcache >=1.7.0
    - google-cloud-monitoring >=2.18.0
    - google-cloud-orchestration-airflow >=1.10.0
    - google-cloud-os-login >=2.9.1
    - google-cloud-pubsub >=2.24.0
    - google-cloud-redis >=2.12.0
    - google-cloud-secret-manager >=2.16.0
    - google-cloud-spanner >=3.50.0
    - google-cloud-speech >=2.18.0
    - google-cloud-storage >=2.9.0
    - google-cloud-storage-transfer >=1.13.0
    - google-cloud-tasks >=2.13.0
    - google-cloud-texttospeech >=2.14.1
    - google-cloud-translate >=3.16.0
    - google-cloud-videointelligence >=2.11.0
    - google-cloud-vision >=3.4.0
    - google-cloud-workflows >=1.10.0
    - google-cloud-run >=0.10.0
    - google-cloud-batch >=0.13.0
    - grpcio-gcp >=0.2.2
    - httpx >=0.25.0
    - looker-sdk >=22.4.0,!=24.18.0
    - pandas-gbq >=0.7.0
    - if: match(python, "<3.13")
      then: pandas >=2.1.2
      else: pandas >=2.2.3
    - proto-plus >=1.26.0
    - pyarrow >=18.0.0
    - python-slugify >=7.0.0
    - sqlalchemy-bigquery >=1.2.1
    - sqlalchemy-spanner >=1.6.2
    - tenacity >=8.3.0
    - immutabledict >=4.2.0
    - types-protobuf >=5.27.0,!=5.29.1.20250402
 

tests:
  - python:
      imports:
        - airflow.providers.google
      pip_check: true

about:
  summary: Provider package apache-airflow-providers-google for Apache Airflow
  license: Apache-2.0
  license_file:
    - LICENSE
    - NOTICE
  homepage: https://github.com/apache/airflow/
  repository: https://github.com/apache/airflow/
  documentation: https://airflow.apache.org/docs/apache-airflow-providers-google/stable/index.html

extra:
  recipe-maintainers:
    - xylar
